#################
### AUTOSTART ###
#################

exec-once = ~/.config/waybar/scripts/launch.sh
exec-once = nm-applet --indicator             # Wi-Fi
exec-once = blueman-applet                   # Bluetooth
exec-once = awww-daemon 2>/dev/null &
exec-once = wal -i /home/zogoue_charles/Images/Wallpapers/od_outrun_wave.png && ~/.config/hypr/scripts/refresh_colors.sh
exec-once = sleep 1 && awww restore --transition-type wave --transition-angle 45 --transition-duration 2
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
# Agent polkit (élévations GUI : blueman, gnome-disks, montages…)
# Nécessite le paquet : yay -S hyprpolkitagent
exec-once = systemctl --user start hyprpolkitagent
exec-once = swayosd-server
exec-once = swayosd-libinput-backend
exec-once = hypridle
exec-once = hyprpm reload -n
exec-once = rclone mount gdrive: /home/zogoue_charles/google-drive --vfs-cache-mode writes --vfs-cache-max-age 24h --vfs-cache-max-size 5G &
