# fichiers importés
source = ~/.config/hypr/modules/moniteurs.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/variables.conf
source = ~/.cache/wal/colors-hyprland.conf
source = ~/.config/hypr/modules/apparence.conf
source = ~/.config/hypr/modules/animations.conf
source = ~/.config/hypr/modules/dispositions-des-fenetres.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/media-controls.conf
source = ~/.config/hypr/modules/raccourcis-clavier.conf
source = ~/.config/hypr/modules/plugins.conf
