general {
    lock_cmd = pidof hyprlock || hyprlock       # Commande pour verrouiller
    before_sleep_cmd = loginctl lock-session    # Verrouiller avant la mise en veille
    after_sleep_cmd = hyprctl dispatch dpms on  # Rallumer l'écran après le réveil
}

listener {
    timeout = 1800                               # 30 minutes
    on-timeout = loginctl lock-session           # Verrouille l'écran
}

listener {
    timeout = 1200                               # 20 minutes (avant le lock à 30 min)
    on-timeout = hyprctl dispatch dpms off       # Éteint l'écran pour économiser la batterie
    on-resume = hyprctl dispatch dpms on         # Rallume au mouvement
}

listener {
    timeout = 2700                               # 45 minutes : mise en veille (économie batterie)
    on-timeout = systemctl suspend
}
