# Import des couleurs pywal
source = ~/.cache/wal/colors-hyprland.conf

# ─── BACKGROUND ───────────────────────────────────────────
background {
    monitor =
    path = /home/zogoue_charles/.cache/wal/current_wallpaper.png
    blur_passes = 1            # Réduit pour mieux voir le katana
    blur_size = 4
    contrast = 0.8             # Plus sombre pour faire ressortir le texte
    brightness = 0.6
    vibrancy = 0.1
}

# ─── HEURE (En haut à gauche) ──────────────────────────────
label {
    monitor =
    text = $TIME
    color = $foreground
    font_size = 90             # Plus grand pour l'effet "Cyber"
    font_family = JetBrainsMono Nerd Font Bold
    position = 70, -80         # Décalage par rapport au coin
    halign = left
    valign = top
}

# ─── DATE (Sous l'heure) ───────────────────────────────────
label {
    monitor = 
    text = cmd[update:60000] echo "— $(LC_TIME=fr_FR.UTF-8 date +'%A . %B %d') —" | tr '[:lower:]' '[:upper:]'
    color = alpha($foreground, 0.7)
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 140, -230
    halign = left
    valign = top
}

# ─── NOM D'UTILISATEUR (En bas à droite) ──────────────────
label {
    monitor =
    text = Z O G O U E          # Ton nom stylisé comme sur l'image
    color = $foreground
    font_size = 24
    font_family = JetBrainsMono Nerd Font Bold
    position = -100, 140
    halign = right
    valign = bottom
}

# ─── CHAMP MOT DE PASSE (Discret, en bas à droite) ───────
input-field {
    monitor =
        size = 250, 40
        outline_thickness = 5      # Plus fin pour rester minimaliste
        dots_size = 0.25
        dots_spacing = 0.4
        dots_center = true
        dotts_fade_time = 200
# C'est ici qu'on définit le symbole de remplacement
        dots_text_format = ✦

        rounding = 0               # Look carré comme sur l'image
        outer_color = $color4
        inner_color = rgba(0, 0, 0, 0.0) # Entièrement transparent
        font_color = rgb(255, 255, 255)

        fade_on_empty = true
        placeholder_text =         # Laisser vide pour le minimalisme

        check_color = $color2
        fail_color = $color1

        position = -80, 85
        halign = right
        valign = bottom
}
