# Import des couleurs de ton wallpaper
source = ~/.cache/wal/colors-hyprland.conf

background {
    monitor =
    path = /home/zogoue_charles/Images/Wallpaper/od_pacman.png  # Utilise ton fond d'écran actuel
    blur_passes = 2    # Effet de flou comme sur iOS/GNOME
    contrast = 0.8916
    brightness = 0.8172
}

# Champ de saisie (Input) - Style "Bulle"
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $color4  # Ta couleur accentuée de Waybar
    inner_color = alpha($color0, 0.6) # Fond sombre transparent
    font_color = $foreground
    fade_on_empty = true
    placeholder_text = <i>Mot de passe...</i>
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
}

# Horloge (Design épuré)
label {
    monitor =
    text = $TIME
    color = $foreground
    font_size = 64
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 80
    halign = center
    valign = center
}
