# --- AUTOSTART (Ordre optimisé pour le Rice) ---
exec-once = ~/.config/waybar/scripts/launch.sh
exec-once = nm-applet --indicator             # Wi-Fi
#exec-once = blueman-applet                   # Bluetooth
exec-once = swww-daemon && swww img /home/zogoue_charles/Images/Wallpaper/od_pacman.png
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = sleep 0.5 && hyprpm reload        # hyprpm aussi bénéficie d'un délai
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = swayosd-server
exec-once = hypridle
exec-once = sleep 2 && 1password --silent     # 1password après tout le reste
