# --- AUTOSTART (Ordre optimisé pour le Rice) ---
exec-once = ~/.config/waybar/scripts/launch.sh
exec-once = nm-applet --indicator             # Wi-Fi
#exec-once = blueman-applet                   # Bluetooth
exec-once = awww-daemon 2>/dev/null &
exec-once = ln -sf /bin/true /usr/bin/swww-daemon
exec-once = sleep 1 && awww restore --transition-type wave --transition-angle 45 --transition-duration 2
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = sleep 0.5 && hyprpm reload        # hyprpm aussi bénéficie d'un délai
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = swayosd-server
exec-once = hypridle
