# --- DISPOSITION DES FENÊTRES ---
dwindle {
    pseudotile = yes
    preserve_split = yes
}

windowrule = match:class waypaper, float true
windowrule = match:class waypaper, center true
windowrule = match:class waypaper, size 400 500

windowrule = match:class org.gnome.Calculator, float true
windowrule = match:class org.gnome.calculator, center true
windowrule = match:class org.gnome.calculator, size 400 600

# Envoyer Obsidian dans le workspace spécial
windowrule = match:class obsidian, workspace special

# Centrer et redimensionner la fenêtre pour un look "tiroir" propre
windowrule = match:class obsidian, float true
windowrule = match:class obsidian, center true
windowrule = match:class obsidian, size 80% 80%

# Redimensionner les fenêtres (e = direction, pixels)
binde = SUPER ALT, right, resizeactive, 30 0
binde = SUPER ALT, left, resizeactive, -30 0
binde = SUPER ALT, up, resizeactive, 0 -30
binde = SUPER ALT, down, resizeactive, 0 30
