#################################
###      MEDIA CONTROLS       ###
#################################

# --- Volume (Style GNOME avec SwayOSD) ---
# Augmenter, Diminuer, Muet
bindel = , XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
bindel = , XF86AudioLowerVolume, exec, swayosd-client --output-volume lower
bindl  = , XF86AudioMute, exec, swayosd-client --output-volume mute-toggle

# --- Luminosité écran (Spécifique MacBook Air) ---
# Utilise désormais SwayOSD pour le retour visuel
bindel = , XF86MonBrightnessUp, exec, swayosd-client --brightness raise
bindel = , XF86MonBrightnessDown, exec, swayosd-client --brightness lower

# --- Rétroéclairage du clavier (F5 et F6) ---
# On garde brightnessctl ici, mais avec l'affichage SwayOSD dédié au clavier
bindel = , XF86KbdBrightnessUp, exec, swayosd-client --caps-lock-led apple::kbd_backlight --brightness raise
bindel = , XF86KbdBrightnessDown, exec, swayosd-client --caps-lock-led apple::kbd_backlight --brightness lower

# --- Contrôles Media (F7, F8, F9) ---
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
bindl = , XF86AudioNext, exec, playerctl next
