#################################
###      MEDIA CONTROLS       ###
#################################

# Volume : Augmenter (limité à 100%), Diminuer, Muet
bindle = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && pkill -RTMIN+8 waybar
bindle = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && pkill -RTMIN+8 waybar
bindl  = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && pkill -RTMIN+8 waybar

# Luminosité écran (Spécifique MacBook Air)
binde = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
binde = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# F8 : Play/Pause
bind = , XF86AudioPlay,  exec, playerctl play-pause

# F7 : Précédent (Previous)
bind = , XF86AudioPrev,  exec, playerctl previous

# F9 : Suivant (Next)
bind = , XF86AudioNext,  exec, playerctl next

# Rétroéclairage du clavier (F5 et F6)
binde = , XF86KbdBrightnessUp, exec, brightnessctl -d "apple::kbd_backlight" set 10%+
binde = , XF86KbdBrightnessDown, exec, brightnessctl -d "apple::kbd_backlight" set 10%-