##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Configuration du terminal flottant (Syntaxe V2)
windowrule = match:class floating_kitty, float true
windowrule = match:class floating_kitty, center true
windowrule = match:class floating_kitty, size 1000 600
windowrule = match:class floating_kitty, opacity 0.95

windowrule = match:class waypaper, float true
windowrule = match:class waypaper, center true
windowrule = match:class waypaper, size 400 500

windowrule = match:class org.gnome.Calculator, float true
windowrule = match:class org.gnome.calculator, center true
windowrule = match:class org.gnome.calculator, size 400 600

windowrule = match:class blueman-manager, float true
windowrule = match:class blueman-manager, center true
windowrule = match:class blueman-manager, size 600 400

# Envoyer Obsidian dans le workspace spécial
windowrule = match:class obsidian, workspace special

windowrule = match:class Bitwarden, float true
windowrule = match:class Bitwarden, center true

# Redimensionner les fenêtres (e = direction, pixels)
binde = SUPER ALT, right, resizeactive, 30 0
binde = SUPER ALT, left, resizeactive, -30 0
binde = SUPER ALT, up, resizeactive, 0 -30
binde = SUPER ALT, down, resizeactive, 0 30
